/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package paqueteturistico.vista;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import paqueteturistico.control.DestinoData;
import paqueteturistico.modelo.Conexion;
import paqueteturistico.modelo.Destino;

/**
 *
 * @author user
 */
public class DestinoVista extends javax.swing.JInternalFrame {
 private DestinoData destinoData=null;
 private Conexion conexion=null;
    private Destino destino=null;
    private ArrayList <Destino> listaDestinos=null;
    /**
     * Creates new form DestinoVista
     */
    public DestinoVista() {
     try {
         conexion =new Conexion();
          destinoData= new DestinoData(conexion);
          
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(DestinoVista.class.getName()).log(Level.SEVERE, null, ex);
     }
        initComponents();
    }
    public void cargardestinos(){
   listaDestinos=(ArrayList<Destino>) destinoData.obtenerDestinos();
     jcDestino.removeAllItems();
      for(Destino i: listaDestinos){
          destino=i;
          jcDestino.addItem(destino);
       }
      jcDestino.setSelectedItem(null);
}
    private void reset(){
        jtCiudad.setText("");
        jtPais.setText("");
        jchActivo.setSelected(false);
        jcDestino.setSelectedItem(null);
    }
    private void desactivartodo(){
        jtPais.setEnabled(false);
        jtCiudad.setEnabled(false);
        jchActivo.setEnabled(false);
        jcDestino.setEnabled(false);
        jbGuardar.setEnabled(false);
        jbBorrar.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtPais = new javax.swing.JTextField();
        jtCiudad = new javax.swing.JTextField();
        jchActivo = new javax.swing.JCheckBox();
        jcDestino = new javax.swing.JComboBox<>();
        jbBorrar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jrBorrar = new javax.swing.JRadioButton();
        jrEditar = new javax.swing.JRadioButton();
        jrNuevo = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jbSalir = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Engravers MT", 3, 18)); // NOI18N
        jLabel1.setText("Destino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Pais Destino :");

        jLabel3.setText("Ciudad destino :");

        jLabel4.setText("Activo :");

        jLabel5.setText("Destino");

        jtPais.setEnabled(false);
        jtPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPaisKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtPaisKeyTyped(evt);
            }
        });

        jtCiudad.setEnabled(false);
        jtCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtCiudadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtCiudadKeyTyped(evt);
            }
        });

        jchActivo.setEnabled(false);

        jcDestino.setEnabled(false);
        jcDestino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcDestinoItemStateChanged(evt);
            }
        });

        jbBorrar.setText("Borrar");
        jbBorrar.setEnabled(false);
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.setEnabled(false);
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jchActivo)
                            .addComponent(jtPais)
                            .addComponent(jcDestino, 0, 173, Short.MAX_VALUE)
                            .addComponent(jtCiudad)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jbBorrar)
                        .addGap(39, 39, 39)
                        .addComponent(jbGuardar)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jchActivo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBorrar)
                    .addComponent(jbGuardar))
                .addGap(14, 14, 14))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 51, 51), null, null));

        jLabel6.setText("Accion :");

        jrBorrar.setBackground(new java.awt.Color(153, 255, 153));
        buttonGroup1.add(jrBorrar);
        jrBorrar.setText("Borrar");
        jrBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrBorrarActionPerformed(evt);
            }
        });

        jrEditar.setBackground(new java.awt.Color(153, 255, 153));
        buttonGroup1.add(jrEditar);
        jrEditar.setText("Editar");
        jrEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrEditarActionPerformed(evt);
            }
        });

        jrNuevo.setBackground(new java.awt.Color(153, 255, 153));
        buttonGroup1.add(jrNuevo);
        jrNuevo.setText("Nuevo");
        jrNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrBorrar)
                    .addComponent(jrEditar)
                    .addComponent(jrNuevo))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jrBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jrEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrNuevo)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jbSalir)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jbSalir)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrBorrarActionPerformed
       //primera parte borrar
        if(jrBorrar.isSelected()){
            reset();
           desactivartodo();
           jcDestino.setEnabled(true);
           cargardestinos();
       }
    }//GEN-LAST:event_jrBorrarActionPerformed

    private void jcDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcDestinoItemStateChanged
       //segunda parte borrar
        if(jrBorrar.isSelected()&&jcDestino.getSelectedItem()!=null){
             jbBorrar.setEnabled(true);
       }
        else if(jrBorrar.isSelected()){
         
         jbBorrar.setEnabled(false);
    }
        //segundaparte Editar
        if (jrEditar.isSelected()&&jcDestino.getSelectedItem()!=null){
            //cargar los datos a los editores
            destino=(Destino) jcDestino.getSelectedItem();
            jtPais.setEnabled(true);
            jtPais.setText(destino.getPaisDestino());
            jtCiudad.setEnabled(true);
            jtCiudad.setText(destino.getCiudadDestino());
            jchActivo.setEnabled(true);
            jchActivo.setSelected(destino.isActivo());
            jbGuardar.setEnabled(true);
            //---------------------------------------------
        }
    }//GEN-LAST:event_jcDestinoItemStateChanged

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
      //tercer parte Borrar
        if(jrBorrar.isSelected()){
          destino=(Destino) jcDestino.getSelectedItem();
          destinoData.borrarDestino(destino.getIdDestino());
          reset();
      }
        
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jrEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrEditarActionPerformed
        if (jrEditar.isSelected()){
            reset();
           desactivartodo();
           jcDestino.setEnabled(true);
           cargardestinos();
        }
    }//GEN-LAST:event_jrEditarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
       // ultima parte Editar
        if (jrEditar.isSelected()){
            destino.setPaisDestino(jtPais.getText());
            destino.setCiudadDestino(jtCiudad.getText());
            destino.setActivo(jchActivo.isSelected());
            destinoData.modificarDestino(destino);
            reset();
             desactivartodo();
             jcDestino.setEnabled(true);
            }
        
        //ultima parte nuevo
        if (jrNuevo.isSelected()){
            destino=new Destino();
             destino.setPaisDestino(jtPais.getText());
            destino.setCiudadDestino(jtCiudad.getText());
            destino.setActivo(jchActivo.isSelected());
            destinoData.guardarDestino(destino);
            reset();
             desactivartodo();
             jtPais.setEnabled(true);
            
        }
        
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jrNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrNuevoActionPerformed
       // primera parte nuevo
        if (jrNuevo.isSelected()){
           reset();
           desactivartodo();
           jtPais.setEnabled(true);
        }  
       
    }//GEN-LAST:event_jrNuevoActionPerformed

    private void jtPaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPaisKeyReleased
    //segunda partye nuevo
        if (jrNuevo.isSelected()&&jtPais.getText().length()!=0){
        jtCiudad.setEnabled(true);
    }
    else if (jrNuevo.isSelected()){
        jtCiudad.setEnabled(false);
        
    }
    }//GEN-LAST:event_jtPaisKeyReleased

    private void jtCiudadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCiudadKeyReleased
       //tercer parte nuevo
        if (jrNuevo.isSelected()&&jtCiudad.getText().length()!=0) {
          jchActivo.setEnabled(true);
          jbGuardar.setEnabled(true);
       }
       else if (jrNuevo.isSelected()){
        jchActivo.setEnabled(false);
          jbGuardar.setEnabled(false);
        }
    }//GEN-LAST:event_jtCiudadKeyReleased

    private void jtPaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPaisKeyTyped
      char c = evt.getKeyChar();
 if ((c<'a'||c>'z')&&(c<'A'||c>'Z')&& c !=KeyEvent.VK_SPACE){
     evt.consume();}
        
    }//GEN-LAST:event_jtPaisKeyTyped

    private void jtCiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCiudadKeyTyped
      char c = evt.getKeyChar();
 if ((c<'a'||c>'z')&&(c<'A'||c>'Z')&& c !=KeyEvent.VK_SPACE){
     evt.consume();}
    
    }//GEN-LAST:event_jtCiudadKeyTyped

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Destino> jcDestino;
    private javax.swing.JCheckBox jchActivo;
    private javax.swing.JRadioButton jrBorrar;
    private javax.swing.JRadioButton jrEditar;
    private javax.swing.JRadioButton jrNuevo;
    private javax.swing.JTextField jtCiudad;
    private javax.swing.JTextField jtPais;
    // End of variables declaration//GEN-END:variables
}
