/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteturistico.vista;

import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import paqueteturistico.control.AlojamientoData;
import paqueteturistico.control.ClienteData;
import paqueteturistico.control.DestinoData;
import paqueteturistico.control.MenuData;
import paqueteturistico.control.PaqueteData;
import paqueteturistico.control.TransporteData;
import paqueteturistico.modelo.Alojamiento;
import paqueteturistico.modelo.Cliente;
import paqueteturistico.modelo.Conexion;
import paqueteturistico.modelo.Destino;
import paqueteturistico.modelo.Menu;
import paqueteturistico.modelo.Paquete;
import paqueteturistico.modelo.Transporte;


/**
 *
 * @author Leonardo
 */
public final class PaqueteVista extends javax.swing.JInternalFrame {
    private DestinoData destinoData;
    
    private ArrayList <Cliente> listaClientes;
    private ArrayList <Destino> listaDestinos;
    private ArrayList <Transporte> listaTransportes;
    private ArrayList <Transporte> listaTransportesXDestino;
    private ArrayList <Alojamiento> listaAlojamientos;
    private ArrayList <Menu> listaMenues;
    private ArrayList <Paquete> listaPaquetes;
    private ClienteData clienteData;
    private TransporteData transporteData;
    private AlojamientoData alojamientoData;
    private PaqueteData paqueteData;
    private MenuData menuData;
    private Conexion conexion;
    
    

    /**
     * Creates new form PaqueteVista
     */
    public PaqueteVista() {
        initComponents();    
        
        try {
            
           conexion = new Conexion();
           clienteData= new ClienteData(conexion);
           destinoData = new DestinoData(conexion);
           transporteData = new TransporteData(conexion);
           alojamientoData = new AlojamientoData(conexion);
           menuData = new MenuData(conexion);
           paqueteData = new PaqueteData(conexion);
           listaClientes = (ArrayList) clienteData.buscarClientes();
           listaDestinos = (ArrayList) destinoData.obtenerDestinos();
           listaTransportes = (ArrayList)transporteData.obtenerTransportes();
           listaTransportesXDestino = (ArrayList)transporteData.obtenerTransportesXDestino(WIDTH);
           jtImporteTotal.setEditable(false);
           listaAlojamientos = (ArrayList)alojamientoData.buscarAlojamientos();
           listaMenues = (ArrayList)menuData.buscarMenues();
           listaPaquetes = (ArrayList)paqueteData.obtenerPaquetes();
           cargarDestinos();
           cargarClientes();
           //cargarDatos();
            
            
        } catch (ClassNotFoundException ex) {
            System.out.println("error" + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbDestino = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbTransporte = new javax.swing.JComboBox<>();
        cbAlojamiento = new javax.swing.JComboBox<>();
        cbMenu = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtImporteTotal = new javax.swing.JTextField();
        jtCantPasajeros = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcAlta = new javax.swing.JCheckBox();
        jcBaja = new javax.swing.JCheckBox();
        jdFechai = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jtcantDias = new javax.swing.JTextField();
        jbCalcular = new javax.swing.JButton();
        jdFechar = new com.toedter.calendar.JDateChooser();
        jbSalir = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jcMedia = new javax.swing.JCheckBox();
        jbLimpiar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();

        jTextField1.setText("jTextField1");

        jLabel12.setText("Media");

        jLabel11.setText("Alta");

        jRadioButton1.setText("jRadioButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        jLabel1.setText("Destino : ");

        jLabel2.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jLabel2.setText(" Paquete");

        cbDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDestinoActionPerformed(evt);
            }
        });

        jLabel3.setText("Transporte :");

        jLabel4.setText("Alojamiento :");

        jLabel5.setText("Menu :");

        jLabel6.setText("Cant.Pasajeros :");

        jLabel7.setText("Importe total  $");

        jtCantPasajeros.setText("1");

        jLabel8.setText("Fecha inicio");

        jLabel9.setText("Fecha regreso");

        jLabel10.setText("Temporada");

        jcAlta.setText("Alta");
        jcAlta.setEnabled(false);
        jcAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcAltaActionPerformed(evt);
            }
        });

        jcBaja.setText("Baja");
        jcBaja.setToolTipText("");
        jcBaja.setEnabled(false);

        jLabel13.setText("Cantidad dias :");

        jtcantDias.setEnabled(false);

        jbCalcular.setText("Calcular");
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });

        jdFechar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jdFecharAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jcMedia.setText("Media");
        jcMedia.setEnabled(false);

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jLabel14.setText("Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSalir)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbTransporte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbAlojamiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbMenu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbBuscar)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(21, 21, 21)
                                .addComponent(jdFechai, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jcBaja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcMedia))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcAlta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel13)
                        .addGap(22, 22, 22)
                        .addComponent(jtcantDias, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtCantPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jbCalcular)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jtImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel14)
                        .addGap(43, 43, 43)
                        .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcAlta)
                            .addComponent(jcMedia)
                            .addComponent(jcBaja)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdFechai, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdFechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtcantDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtCantPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jbCalcular))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir)
                    .addComponent(jbLimpiar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     public int calcularDias(JCalendar fi, JCalendar  ff){
        int dias=-1;
        if(fi.getDate()!=null && ff.getDate()!=null){
            Calendar inicio=fi.getCalendar();
            Calendar termino=ff.getCalendar();
            
           
            while (inicio.before(termino)||inicio.equals(termino)){
                dias++;
                inicio.add(Calendar.DATE,1);
            }
            
        } 
        return dias;       
    }
     
     
     
     public void limpiar(){
        
         
        cbCliente.removeAllItems();
        cbTransporte.removeAllItems();
        cbAlojamiento.removeAllItems();
        cbMenu.removeAllItems();   
        jcBaja.setSelected(false);
        jcMedia.setSelected(false);
        jcAlta.setSelected(false);
        
        jtcantDias.setText("");
        jtCantPasajeros.setText("");
        jtImporteTotal.setText("");
        jdFechai.setDateFormatString("");
        jdFechar.setDateFormatString("");
                
     }
     
    private void cbDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDestinoActionPerformed
       //cargarDatos();

    }//GEN-LAST:event_cbDestinoActionPerformed

    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
//        // TODO add your handling code here:
        JCalendar fi= jdFechai.getJCalendar(); 
        JCalendar ff= jdFechar.getJCalendar();
        
        Date f1=jdFechai.getDate();
        Date f2=jdFechar.getDate();
     
        String dias= calcularDias(fi,ff)+""; // calcula los dias entre fechas
        jtcantDias.setText(dias);
        //ff.setMinSelectableDate(fi.getDate());
        
        if (f1.compareTo(f2) > 0)
    {
       JOptionPane.showMessageDialog(null, "La fecha de regreso debe ser posterior a la de inicio");
    }
        
       
        
        LocalDate fini = f2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        int mesi = fini.getMonthValue();
        fini.getDayOfMonth();
        
        int band = 0;
        
        switch (mesi) {
            case 1:
            case 7:
                jcAlta.setSelected(true);
                band=1;
                break;
            case 2:
            case 6:
                jcMedia.setSelected(true);
                band=2;
                break;
            default:
                jcBaja.setSelected(true);
                break;
        }
        
        
        Transporte tr=(Transporte)cbTransporte.getSelectedItem();
        Alojamiento al =(Alojamiento)cbAlojamiento.getSelectedItem();
        Menu me =(Menu)cbMenu.getSelectedItem();
        
       
        float impT=tr.getPrecioViaje();
        float impA=al.getPrecioNoche();
        float impM=me.getPrecioMenu();
        int cantDias=Integer.parseInt(dias);
        int cantPas=Integer.parseInt(jtCantPasajeros.getText());
        
        float total=((impT*2)+(impA*cantDias)+(impM*cantDias))*cantPas;
        
        
        if(band==1){
            
            total=(float) (total*1.3);
        }if (band==2){
            total=(float) (total*1.15);
        }
        
        String t=total+"";
        jtImporteTotal.setText(t);
           
    }//GEN-LAST:event_jbCalcularActionPerformed

   
    
    private void jdFecharAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jdFecharAncestorAdded
        // TODO add your handling code here:
//        JCalendar fi= jdFechai.getJCalendar(); 
//        JCalendar ff= jdFechar.getJCalendar();
//        
//        Date f1=jdFechai.getDate();
//        Date f2=jdFechar.getDate();
//        
//        
//        String dias= calcularDias(fi,ff)+""; // calcula los dias entre fechas
//        jtcantDias.setText(dias);
//        
//        if (f1.compareTo(f2) > 0)
//    {
//       JOptionPane.showMessageDialog(null, "La fecha de regreso debe ser posterior a la de inicio");
//    }
//     
//        
    }//GEN-LAST:event_jdFecharAncestorAdded

    private void jcAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcAltaActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        cargarDatos();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
        
        
    }//GEN-LAST:event_jbLimpiarActionPerformed

    
    public void cargarDatos(){
    
        Destino des =(Destino)cbDestino.getSelectedItem();
        int idDest=des.getIdDestino();
        listaTransportesXDestino = (ArrayList)transporteData.obtenerTransportesXDestino(idDest);
        
        TransporteData td=null;
      
        for(Transporte t: listaTransportesXDestino){
            //if(t.getDestino().getIdDestino()==des.getIdDestino()){
              //if(td.obtenerTransportesXDestino(des.getIdDestino())!=null)  
                cbTransporte.addItem(t);
                
            
        }

          //cbTransporte.addItem((t.obtenerTransportesXDestino(des.getIdDestino());
             
        for(Alojamiento a: listaAlojamientos){
            if(des.getIdDestino()==a.getDestino().getIdDestino()){
                cbAlojamiento.addItem(a);
            }
        }
        
        Alojamiento alo=(Alojamiento)cbAlojamiento.getSelectedItem();
               
        for(Menu m: listaMenues){
            if(alo.getIdAlojamiento()==m.getAlojamiento().getIdAlojamiento()){
                cbMenu.addItem(m);
            }
     
    }
    }
   

   
    public void cargarDestinos(){
        for(Destino i: listaDestinos){
            cbDestino.addItem(i);
        }
       
     }
    
    public void cargarClientes(){
        for(Cliente c: listaClientes){
            cbCliente.addItem(c);
        }
       
     }
     
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<Alojamiento> cbAlojamiento;
    private javax.swing.JComboBox<Cliente> cbCliente;
    private javax.swing.JComboBox<Destino> cbDestino;
    private javax.swing.JComboBox<Menu> cbMenu;
    private javax.swing.JComboBox<Transporte> cbTransporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JCheckBox jcAlta;
    private javax.swing.JCheckBox jcBaja;
    private javax.swing.JCheckBox jcMedia;
    private com.toedter.calendar.JDateChooser jdFechai;
    private com.toedter.calendar.JDateChooser jdFechar;
    private javax.swing.JTextField jtCantPasajeros;
    private javax.swing.JTextField jtImporteTotal;
    private javax.swing.JTextField jtcantDias;
    // End of variables declaration//GEN-END:variables

    private void calcularDias(Date fi, Date ff) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
